package handlers

// DefaultSiteContent returns placeholder site content seeded into the DB on first run.
// Edit these values via the admin UI after setup, or change them here before first launch.
func DefaultSiteContent() any {
	return map[string]any{
		"brand": map[string]any{
			"name":          "Your Project Name",
			"logoAlt":       "Your Project logo",
			"navLines":      []string{"Your Project", "Name"},
			"tagline":       "A short tagline describing what you do.",
			"email":         "hello@your-domain.com",
			"facebookLink":  "https://www.facebook.com/your-page",
			"instagramLink": "https://www.instagram.com/your-handle",
		},
		"location": map[string]any{
			"address":    "123 Main Street, Your City, ST 00000",
			"mapLink":    "https://www.google.com/maps?q=123+Main+Street",
			"visitLabel": "Visit us",
			"hours":      "Mon–Fri 9:00 AM–5:00 PM",
			"phone":      "+10000000000",
		},
		"home": map[string]any{
			"eyebrow":          "Your value proposition",
			"headline":         "A compelling headline for your homepage",
			"serviceAreaLine":  "Serving your region",
			"description":      "Describe your project, what you offer, and why customers choose you.",
			"trustLine":        "Fast shipping • Secure checkout • Satisfaction guaranteed",
			"instagramCta":     "Follow us on Instagram",
			"instagramLink":    "https://www.instagram.com/your-handle",
			"ctaPrimary":       "Shop Now",
			"ctaSecondary":     "Contact Us",
			"newArrivalsTitle": "New arrivals",
			"featuredTitle":    "Featured items",
			"categoriesTitle":  "Shop by category",
			"categories": []map[string]any{
				{"title": "Category A", "detail": "Description of category A"},
				{"title": "Category B", "detail": "Description of category B"},
				{"title": "Category C", "detail": "Description of category C"},
			},
			"howItWorksTitle": "How it works",
			"howItWorks": []map[string]any{
				{"title": "Browse", "detail": "Explore our catalog online or in person."},
				{"title": "Order", "detail": "Place your order with ease."},
				{"title": "Receive", "detail": "Get your items delivered or pick them up."},
			},
			"curationTitle":  "Quality you can count on.",
			"curationDetail": "Every item is carefully selected and verified before it reaches you.",
			"storeInfo":      "Open Mon–Fri 9AM–5PM • Fast shipping available",
			"emptyArrivals":  "No items available right now — check back soon.",
			"localIntent":    "Your Project Name proudly serves customers in your area.",
			"visitCta":       "Visit our store",
			"testimonialsTitle": "What our customers are saying",
			"testimonials": []map[string]any{
				{"name": "A. Customer", "location": "City, ST", "quote": "Great product and fast shipping. Highly recommend!"},
				{"name": "B. Buyer", "location": "City, ST", "quote": "Excellent quality and friendly service. Will buy again."},
				{"name": "C. Client", "location": "City, ST", "quote": "Exactly as described. Very happy with my purchase."},
			},
			"waitlistTitle":       "Looking for something specific?",
			"waitlistDescription": "Tell us what you need and we'll let you know when it's available.",
			"waitlistPlaceholder": "Your email address",
			"waitlistButton":      "Join the waitlist",
		},
		"shop": map[string]any{
			"title":       "Shop",
			"description": "Browse our catalog of quality items.",
			"filters": map[string]any{
				"categoryLabel": "Category",
				"typeLabel":     "Type",
				"applyLabel":    "Apply filters",
				"clearLabel":    "Clear",
			},
			"searchPlaceholder": "Search by name, type, brand...",
			"emptyMessage":      "No items available right now — check back soon.",
			"reserveCta":        "Inquire / Order",
			"smsCta":            "Order by text",
			"emailCta":          "Order by email",
			"similarCta":        "Ask about similar items",
			"smsNumber":         "+10000000000",
			"smsTemplate":       "Hi, I want to order {item} for {price}.",
		},
		"decor": map[string]any{
			"eyebrow":     "Accessories",
			"title":       "Add-ons & accessories",
			"description": "Complementary items that pair well with our main catalog.",
			"items": []string{
				"Accessory type 1",
				"Accessory type 2",
				"Accessory type 3",
				"Accessory type 4",
			},
		},
		"contact": map[string]any{
			"eyebrow":          "Get in touch",
			"title":            "Contact us",
			"description":      "Have a question or want to place a custom order? Reach out.",
			"addressLabel":     "Visit us at 123 Main Street, Your City, ST 00000",
			"hoursLabel":       "Hours: Mon–Fri 9:00 AM–5:00 PM",
			"serviceAreaIntro": "We serve customers in our region. Contact us to confirm availability in your area.",
			"nearbyAreasTitle": "Areas we serve",
			"nearbyAreas": []string{
				"City A, ST",
				"City B, ST",
				"City C, ST",
			},
			"form": map[string]any{
				"nameLabel":             "Name",
				"namePlaceholder":       "Your name",
				"emailLabel":            "Email",
				"emailPlaceholder":      "you@email.com",
				"phoneLabel":            "Phone (optional)",
				"phonePlaceholder":      "(555) 123-4567",
				"pickupDeliveryLabel":   "Pickup or delivery",
				"pickupDeliveryOptions": []string{"In-store pickup", "Delivery", "Not sure"},
				"zipLabel":              "Zip (optional)",
				"zipPlaceholder":        "00000",
				"detailsLabel":          "Details",
				"detailsPlaceholder":    "Tell us what you're looking for.",
				"submitLabel":           "Send inquiry",
				"successMessage":        "Thanks! We'll be in touch soon.",
				"errorMessage":          "Something went wrong. Please try again.",
			},
		},
		"about": map[string]any{
			"title":             "About Us",
			"intro":             "We are a dedicated team focused on delivering quality products and exceptional service.",
			"story":             "Our story starts with a passion for what we do. Every item we carry reflects our commitment to quality and our customers' satisfaction.",
			"valuesTitle":       "What guides us",
			"values": []string{
				"Quality products from trusted sources.",
				"Honest, transparent service.",
				"A great experience every time.",
			},
			"ownersTitle":       "Meet the team",
			"ownersDescription": "Our team brings together years of experience and a shared commitment to doing things right.",
			"ownersImageAlt":    "Our team",
		},
		"nav": map[string]any{
			"home":    "Home",
			"shop":    "Shop",
			"contact": "Contact",
			"about":   "About",
		},
	}
}
